### ISSUE TITLE
use as part of node (command line) project

### ISSUE THREAD

**Issue by shaunc** [givanse/broccoli-babel-examples#2]
Thank you for these examples.

I'm trying to start a node project. It will have modules, tests, etc, but no browser support, and should have full access to node modules.

I tried to base my project on the "es6-modules" example, but the fact that this runs in a browser is a hinderance. Do you suppose you could modify the instructions to explain how to strip out the browser stuff? Rebuild in a "watch" mode would be great if that is supported. I guess I should learn more about broccoli, in order to do this myself, but I would be grateful for some pointers, at least. Thanks!

**Comment by givanse** [comment]
Remove the file `src/index.html` and thats it, all the "browser support" stuff is in that file. After that you can delete from `Brocfile.js` the relevant bits. Pretty sure its just a matter of deleting `const indexHtml` and the lines where its used.

You'll have to execute your scripts just like in the first example `es6-fruits` and you can import/export modules just as any Node app. The transpiling process isn't messing with any of that.

**Comment by shaunc** [comment]
Great -- thanks!
